### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by raunakdaga** [raunakdaga/eAbsentee#10]
I don't know much about web security. I only know some key terms like HTTPS and SSL etc. I honestly don't know much about what these mean, or what they do. I know we can require HTTPS through GitHub pages, maybe check if there is something similar for other hosting options?

Reference: https://github.com/TrustTheVote-Project/horatio-server/issues/8

**Comment by sumanthratna** [comment]
If we use Director, we get HTTPS on the sites.tjhsst.edu domain, but we can use CloudFlare with our custom domain to get HTTPS.

**Comment by raunakdaga** [comment]
Consolidated with hosting - will be using PythonAnywhere.com
