### ISSUE TITLE
Validate email addresses

### ISSUE THREAD

**Issue by raunakdaga** [raunakdaga/eAbsentee#26]
As they are being inputted, validate the email addresses to make sure they're legitimate emails.

**Comment by raunakdaga** [comment]
Really no reason to do this - only way to even check would be using confirmation emails, but that's not necessary because this is a form. Instead, account for incorrect email input  by the user by asking for double confirmation from canvasser.

**Comment by sumanthratna** [comment]
We could use NeverBounce to verify emails.
